name: dbt_authorized_models
version: 0.2.0
config-version: 2
require-dbt-version: [">=1.10.0", "<2.0.0"]

dispatch:
  - macro_namespace: dbt_authorized_models
    search_order:
      - dbt_authorized_models

models:
  dbt_authorized_models:
    +enabled: false
